### ISSUE TITLE
无法添加账号，提示：添加失败,检查你的账号密码是否正确或FakeOpen服务异常

### ISSUE THREAD

**Issue by RamenRa** [Yanyutin753/PandoraNext-TokensTool#20]
## 错误截图
![捕获](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/53000259/35a2267f-0129-43cf-a3a7-667c58e33557)

## 环境
Ubuntu 22.04.2 LTS，网关和dns指向旁路由。（windows网络设置相同可以访问openai）
## 部署方式
```
docker run -d \
  --restart=always \
  -u root \
  --name tokensTool \
  --net=host \
  --pid=host \
  --privileged=true \
  -v /home/docker/PandoraNext:/home/docker/PandoraNext \
  -v /var/run/docker.sock:/var/run/docker.sock \
  yangclivia/tokenstool:latest \
  --loginUsername=root \
  --loginPassword=123456  \
  --deployWay=docker \
  --deployPosition=/home/docker/PandoraNext \
  --hotReload=true \
  --pandoara_Ip=127.0.0.1
```

## docker容器日志
```
2023-11-24 09:47:08.705  WARN 124745 --- [           main] c.d.f.scanner.ClassPathClientScanner     : [Forest] No Forest client is found in package '[com.yyandywt99.pandoraNext]'.
2023-11-24 09:47:09.312  INFO 124745 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
2023-11-24 09:47:09.328  INFO 124745 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-11-24 09:47:09.328  INFO 124745 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.79]
2023-11-24 09:47:09.455  INFO 124745 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-11-24 09:47:09.456  INFO 124745 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2851 ms
2023-11-24 09:47:10.249  INFO 124745 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
2023-11-24 09:47:10.680  INFO 124745 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8081 (http) with context path ''
2023-11-24 09:47:10.716  INFO 124745 --- [           main] c.y.pandoraNext.FakeApiToolApplication   : Started FakeApiToolApplication in 5.271 seconds (JVM running for 6.218)
2023-11-24 09:47:10.726  INFO 124745 --- [eduler-Thread-1] c.y.p.controller.apiController           : Ip将采用用户设置：127.0.0.1
2023-11-24 09:47:13.463  INFO 124745 --- [nio-8081-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-11-24 09:47:13.463  INFO 124745 --- [nio-8081-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-11-24 09:47:13.465  INFO 124745 --- [nio-8081-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2023-11-24 09:47:13.507  INFO 124745 --- [nio-8081-exec-1] c.y.p.interceptor.LoginCheckInterceptor  : 请求的url: http://172.16.8.180:8081/api/loginToken
2023-11-24 09:47:13.512  INFO 124745 --- [nio-8081-exec-1] c.y.p.interceptor.LoginCheckInterceptor  : 登录操作, 放行...
2023-11-24 09:47:13.515  INFO 124745 --- [nio-8081-exec-2] c.y.p.interceptor.LoginCheckInterceptor  : 请求的url: http://172.16.8.180:8081/api/seleteToken
2023-11-24 09:47:13.516  INFO 124745 --- [nio-8081-exec-2] c.y.p.interceptor.LoginCheckInterceptor  : Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNzAwODQ2NDE5fQ.JV-r6tFLWrOyFUGRdBwtHjRFwSwamrz6LMOH9zTUzcM
2023-11-24 09:47:13.553  INFO 124745 --- [nio-8081-exec-1] c.y.p.controller.loginColltroller        : eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNzAwODQ2NDE5fQ.JV-r6tFLWrOyFUGRdBwtHjRFwSwamrz6LMOH9zTUzcM
2023-11-24 09:47:13.828  INFO 124745 --- [nio-8081-exec-1] c.y.p.controller.loginColltroller        : 令牌合法，可以正常登录
2023-11-24 09:47:13.828  INFO 124745 --- [nio-8081-exec-2] c.y.p.interceptor.LoginCheckInterceptor  : 令牌合法, 放行
2023-11-24 09:47:13.844  INFO 124745 --- [nio-8081-exec-2] c.y.p.service.impl.apiServiceImpl        : /home/docker/PandoraNext/tokens.json
postHandle ...
postHandle ...
afterCompletion...
afterCompletion...
2023-11-24 09:47:18.236  INFO 124745 --- [nio-8081-exec-3] c.y.p.interceptor.LoginCheckInterceptor  : 请求的url: http://172.16.8.180:8081/api/updateToken
2023-11-24 09:47:18.236  INFO 124745 --- [nio-8081-exec-3] c.y.p.interceptor.LoginCheckInterceptor  : Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNzAwODQ2NDE5fQ.JV-r6tFLWrOyFUGRdBwtHjRFwSwamrz6LMOH9zTUzcM
2023-11-24 09:47:18.237  INFO 124745 --- [nio-8081-exec-3] c.y.p.interceptor.LoginCheckInterceptor  : 令牌合法, 放行
2023-11-24 09:47:19.127  INFO 124745 --- [nio-8081-exec-3] c.y.p.service.impl.apiServiceImpl        : HttpResponseProxy{HTTP/1.1 429 Too Many Requests [Date: Fri, 24 Nov 2023 09:47:19 GMT, Content-Type: application/json, Content-Length: 29, Connection: keep-alive, Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=HjaRag2dW9XMKESfw86eQj8%2Fx8NsKc2zftQkxohSNJKj0wUn6%2BAkqszJJdpFFQQkvi6uzMXYrmdY32ogMRvtmMab0yrhlX9CgPKhcguB1c22Led0u7ndH39wEoOVOGtMLg%3D%3D"}],"group":"cf-nel","max_age":604800}, NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}, Vary: Accept-Encoding, Strict-Transport-Security: max-age=15552000; includeSubDomains; preload, X-Content-Type-Options: nosniff, Server: cloudflare, CF-RAY: 82b0bad41b7d258d-HKG, alt-svc: h3=":443"; ma=86400] ResponseEntityProxy{[Content-Type: application/json,Content-Length: 29,Chunked: false]}}
2023-11-24 09:47:19.140  INFO 124745 --- [nio-8081-exec-3] c.y.p.service.impl.apiServiceImpl        : {"detail":"service overload"}
org.json.JSONException: No value for access_token
        at org.json.JSONObject.get(JSONObject.java:355)
        at org.json.JSONObject.getString(JSONObject.java:515)
        at com.yyandywt99.pandoraNext.service.impl.apiServiceImpl.updateToken(apiServiceImpl.java:334)
        at com.yyandywt99.pandoraNext.service.impl.apiServiceImpl.autoUpdateSimpleToken(apiServiceImpl.java:363)
        at com.yyandywt99.pandoraNext.controller.autoTokenController.toUpdateToken(autoTokenController.java:62)
        at com.yyandywt99.pandoraNext.controller.autoTokenController$$FastClassBySpringCGLIB$$ebecb27a.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:49)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at com.yyandywt99.pandoraNext.controller.autoTokenController$$EnhancerBySpringCGLIB$$de6f33e1.toUpdateToken(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1790)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:829)
2023-11-24 09:47:19.171  INFO 124745 --- [nio-8081-exec-3] c.y.p.controller.apiController           : 重载的PandoraNext服务Url:http://127.0.0.1:8181
2023-11-24 09:47:19.200  INFO 124745 --- [nio-8081-exec-3] c.y.p.controller.apiController           : 重载命令:curl -H "Authorization: Bearer 123456" -X POST "http://127.0.0.1:8181/setup/reload"
2023-11-24 09:47:19.215  INFO 124745 --- [nio-8081-exec-3] c.yyandywt99.pandoraNext.aop.LogAspect   : Result(code=1, msg=success, data=重置PandoraNext服务成功！)

```

**Comment by Yanyutin753** [comment]
大概9点多会出一个一键部署的，到时候可以去看看，不行，你可以加群问群友，这上面看不出来

**Comment by Yanyutin753** [comment]
这个错误很明显接口拿不到token，等接口吧
