### ISSUE TITLE
添加账号问题302

### ISSUE THREAD

**Issue by xupeng19881010** [Yanyutin753/PandoraNext-TokensTool#32]
网页报-------添加失败,检查你的账号密码是否正确或FakeOpen服务异常

后台-------------[nio-8081-exec-6] c.y.p.service.impl.apiServiceImpl        : HttpResponseProxy{HTTP/1.1 302 Found [Location: /site/login?next=%2Fapi%2Fauth%2Flogin, X-Server: PandoraNext/0.4.0, Date: Wed, 29 Nov 2023 14:22:28 GMT, Content-Length: 0] [Content-Length: 0,Chunked: false]}

**Comment by xupeng19881010** [comment]
stderr: org.json.JSONException: End of input at character 0 of 
stderr: 	at org.json.JSONTokener.syntaxError(JSONTokener.java:450)
stderr: 	at org.json.JSONTokener.nextValue(JSONTokener.java:97)
stderr: 	at org.json.JSONObject.<init>(JSONObject.java:155)
stderr: 	at org.json.JSONObject.<init>(JSONObject.java:172)
stderr: 	at com.yyandywt99.pandoraNext.service.impl.apiServiceImpl.updateSessionToken(apiServiceImpl.java:410)
stderr: 	at com.yyandywt99.pandoraNext.service.impl.apiServiceImpl.addToken(apiServiceImpl.java:163)
stderr: 	at com.yyandywt99.pandoraNext.controller.apiController.addToken(apiController.java:73)
stderr: 	at com.yyandywt99.pandoraNext.controller.apiController$$FastClassBySpringCGLIB$$d413ee0a.invoke(<generated>)
stderr: 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
stderr: 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
stderr: 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
stderr: 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
stderr: 	at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:49)
stderr: 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
stderr: 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
stderr: 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
stderr: 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
stderr: 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
stderr: 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
stderr: 	at com.yyandywt99.pandoraNext.controller.apiController$$EnhancerBySpringCGLIB$$48d03fb3.addToken(<generated>)
stderr: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
stderr: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
stderr: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
stderr: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
stderr: 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
stderr: 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
stderr: 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
stderr: 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
stderr: 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
stderr: 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
stderr: 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
stderr: 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
stderr: 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
stderr: 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
stderr: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
stderr: 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
stderr: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
stderr: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
stderr: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
stderr: 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
stderr: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
stderr: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
stderr: 	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
stderr: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
stderr: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
stderr: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
stderr: 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
stderr: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
stderr: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
stderr: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
stderr: 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
stderr: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
stderr: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
stderr: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
stderr: 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
stderr: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
stderr: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
stderr: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
stderr: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
stderr: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
stderr: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
stderr: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
stderr: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
stderr: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
stderr: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
stderr: 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
stderr: 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
stderr: 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
stderr: 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1790)
stderr: 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
stderr: 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
stderr: 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
stderr: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
stderr: 	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by Yanyutin753** [comment]
要双开PandoraNext，可以看看教程

**Comment by jsxupeng** [comment]
已经解决
