### ISSUE TITLE
通过Docker部署的pandora，系统操作是否有效？

### ISSUE THREAD

**Issue by Qianmoxsn** [Yanyutin753/PandoraNext-TokensTool#5]
首先感谢大佬的贡献！！

我使用Docker进行了Pandora Next的部署，同时在docker卷（Volume）下运行了本项目的jar包。

我进行了更改`config.json`的测试，成功修改了配置文件，因此我的运行配置应该是正确的

但我试图使用系统配置进行重启PN时，docker容器并没有重启，页面显示不停的加载。

考虑到此项目应该是以本地部署作为开发环境的，想请问开启/暂停/重启三个命令是否考虑了docker环境下的操作？

顺颂时祺！

**Comment by Yanyutin753** [comment]
来啦，我之前用过docker是可以,这个新代码还没试

**Comment by Yanyutin753** [comment]
我去试验一下，你有改环境变量吗，要把--deployWay=docker,你有做这个吗

**Comment by Qianmoxsn** [comment]
`--deployWay=docker` 是有的

**Comment by Yanyutin753** [comment]
好，我去重新试一下，我改代码没试过，昨天试了docker,今天改了不知道应该错了

**Comment by Yanyutin753** [comment]
好了查明原因了，是因为开始的tokens没加东西，重启就会报错，导致重启不了

**Comment by Yanyutin753** [comment]
确实没注意这个

**Comment by Yanyutin753** [comment]
好了，你看看新的代码

**Comment by Qianmoxsn** [comment]
我尝试部署了新的代码，但并没有成功运行。从前端返回了500错误
```js
GET http://test...com:8081/api/close 500 (Internal Server Error)
```
同时在后端发生了这些错误
```java
2023-11-19 15:57:50.021  INFO 3270904 --- [nio-8081-exec-8] c.y.p.interceptor.LoginCheckInterceptor  : 请求的url: http://test...com:8081/api/close
2023-11-19 15:57:50.022  INFO 3270904 --- [nio-8081-exec-8] c.y.p.interceptor.LoginCheckInterceptor  : Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNzAwNDIyODE3fQ.Vl0pyQPkDAunRFbawEza3x9XZg4AG6QWJTbir5S-_ls
2023-11-19 15:57:50.023  INFO 3270904 --- [nio-8081-exec-8] c.y.p.interceptor.LoginCheckInterceptor  : 令牌合法, 放行
2023-11-19 15:57:50.086  INFO 3270904 --- [nio-8081-exec-8] c.y.p.controller.apiColltroller          : 无法pausePandoraNext服务
afterCompletion...
2023-11-19 15:57:50.097 ERROR 3270904 --- [nio-8081-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: 无法pausePandoraNext服务] with root cause

java.lang.RuntimeException: 无法pausePandoraNext服务
        at com.yyandywt99.pandoraNext.controller.apiColltroller.docker(apiColltroller.java:221) ~[classes!/:0.0.1-SNAPSHOT]
        at com.yyandywt99.pandoraNext.controller.apiColltroller.closeContainer(apiColltroller.java:120) ~[classes!/:0.0.1-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~
......
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.79.jar!/:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.79.jar!/:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.79.jar!/:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

**Comment by Qianmoxsn** [comment]
同时建议在前端处理好500错误以避免页面加载死循环

**Comment by Yanyutin753** [comment]
奇怪 我昨天晚上跑了一次都可以啊 你其他可以吗 重启可以吗

**Comment by Yanyutin753** [comment]
还有你的pandoraNext开了吗
